[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --workspaces --include-workspace-root --legacy-peer-deps"]

[phases.build]
cmds = [
  "cd server && npx prisma generate",
  "npm run build:client",
  "npm run build:server"
]

[start]
cmd = "node server/dist/index.js"
