[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --workspaces --include-workspace-root --legacy-peer-deps"]

[phases.build]
cmds = [
  "npm run build:client",
  "npm run build:server",
  "cd server && npx prisma generate"
]

[start]
cmd = "cd server && npx prisma migrate deploy && node dist/index.js"
